#!/bin/bash

# 将 Cookie 字符串转换为 Netscape 格式
# 支持两种输入格式:
# 1. 浏览器 Cookie 字符串: "name1=value1; name2=value2; ..."
# 2. Netscape/Cookieplain 格式: 每行一个 cookie，tab 分隔
# 用法: ./parse_cookie.sh "cookie字符串" 或 ./parse_cookie.sh /path/to/cookiesplain.txt
#       或 ./parse_cookie.sh (使用默认的 cookiesplain 文件)

RAW_COOKIE="$1"
COOKIE_JAR="$(dirname "$0")/cookies.txt"
DEFAULT_COOKIE_FILE="$(dirname "$0")/cookiesplain"

if [ -z "$RAW_COOKIE" ]; then
    if [ -f "$DEFAULT_COOKIE_FILE" ]; then
        RAW_COOKIE="$(cat "$DEFAULT_COOKIE_FILE")"
        echo "使用默认 cookiesplain 文件"
    else
        echo "用法: $0 \"cookie字符串\" 或 $0 /path/to/cookiesplain.txt"
        echo "或确保存在默认文件: $DEFAULT_COOKIE_FILE"
        exit 1
    fi
fi

# 检测输入格式
if [ -f "$RAW_COOKIE" ]; then
    # 文件格式 (Netscape/Cookieplain)
    INPUT_TYPE="file"
    echo "检测到文件输入格式 (Netscape/Cookieplain)"
else
    # 字符串格式 (浏览器 Cookie)
    INPUT_TYPE="string"
    echo "检测到字符串输入格式 (浏览器 Cookie)"
fi

# 生成 Netscape 格式文件
{
    echo "# Netscape HTTP Cookie File"
    echo "# https://curl.se/docs/http-cookies.html"
    echo "# This file was generated by parse_cookie.sh! Edit at your own risk."
    echo ""

    if [ "$INPUT_TYPE" = "file" ]; then
        # 处理 Netscape/Cookieplain 文件格式
        while IFS=$'\t' read -r domain flag path secure expire name value; do
            # 跳过注释行和空行
            [[ "$domain" =~ ^# ]] && continue
            [ -z "$domain" ] && continue
            
            # 输出 Netscape 格式
            echo -e "${domain}\t${flag}\t${path}\t${secure}\t${expire}\t${name}\t${value}"
        done < "$RAW_COOKIE"
    else
        # 处理浏览器 Cookie 字符串格式
        IFS=';' read -ra COOKIES <<< "$RAW_COOKIE"
        for cookie in "${COOKIES[@]}"; do
            # 去除首尾空白
            cookie=$(echo "$cookie" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')

            # 分离 name 和 value
            name=$(echo "$cookie" | cut -d'=' -f1)
            value=$(echo "$cookie" | cut -d'=' -f2-)

            # 跳过空值
            [ -z "$name" ] && continue

            # 输出 Netscape 格式 (domain, secure, path, expire, name, value)
            # 使用 localhost 作为域名，设置较长的过期时间
            echo -e "localhost\tFALSE\t/\tFALSE\t18934560000\t${name}\t${value}"
        done
    fi
} > "$COOKIE_JAR"

echo "Cookie 已保存到 $COOKIE_JAR"
