configProperties:  
  version: v2  
application:  
  services:  
    - name: __ORIGINAL_DEPLOY_NAME__  
      serviceType: deployment  
      containers:  
        - name: __ORIGINAL_DEPLOY_NAME__  
          dev:  
            image: golang:1.24  
            shell: /bin/bash
